package cayenne_classes;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _InputParamDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InputParamDAO extends CayenneDataObject {

    public static final String COL_NUM_PROPERTY = "colNum";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String ROW_NUM_PROPERTY = "rowNum";
    public static final String TO_MODEL_PROPERTY = "toModel";

    public static final String ID_PK_COLUMN = "ID";

    public void setColNum(Integer colNum) {
        writeProperty("colNum", colNum);
    }
    public Integer getColNum() {
        return (Integer)readProperty("colNum");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setRowNum(Integer rowNum) {
        writeProperty("rowNum", rowNum);
    }
    public Integer getRowNum() {
        return (Integer)readProperty("rowNum");
    }

    public void setToModel(ExcelModelDAO toModel) {
        setToOneTarget("toModel", toModel, true);
    }

    public ExcelModelDAO getToModel() {
        return (ExcelModelDAO)readProperty("toModel");
    }


}
