package mit.excelwrapper.model.auto;

import org.apache.cayenne.CayenneDataObject;

import mit.excelwrapper.model.ExcelModel;

/**
 * Class _InputParam was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InputParam extends CayenneDataObject {

    public static final String COL_NUM_PROPERTY = "colNum";
    public static final String DATA_TYPE_PROPERTY = "dataType";
    public static final String INTERNAL_NAME_PROPERTY = "internalName";
    public static final String ROW_NUM_PROPERTY = "rowNum";
    public static final String MODEL_PROPERTY = "model";

    public static final String ID_PK_COLUMN = "ID";

    public void setColNum(Integer colNum) {
        writeProperty("colNum", colNum);
    }
    public Integer getColNum() {
        return (Integer)readProperty("colNum");
    }

    public void setDataType(String dataType) {
        writeProperty("dataType", dataType);
    }
    public String getDataType() {
        return (String)readProperty("dataType");
    }

    public void setInternalName(String internalName) {
        writeProperty("internalName", internalName);
    }
    public String getInternalName() {
        return (String)readProperty("internalName");
    }

    public void setRowNum(Integer rowNum) {
        writeProperty("rowNum", rowNum);
    }
    public Integer getRowNum() {
        return (Integer)readProperty("rowNum");
    }

    public void setModel(ExcelModel model) {
        setToOneTarget("model", model, true);
    }

    public ExcelModel getModel() {
        return (ExcelModel)readProperty("model");
    }


}
