package mit.simulation.climate.dao;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _CompositeMapDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CompositeMapDAO extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String TO_SIM_CHILDREN_PROPERTY = "toSimChildren";
    public static final String TO_SIM_PARENT_PROPERTY = "toSimParent";

    public static final String ID_PK_COLUMN = "id";

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setToSimChildren(SimulationDAO toSimChildren) {
        setToOneTarget("toSimChildren", toSimChildren, true);
    }

    public SimulationDAO getToSimChildren() {
        return (SimulationDAO)readProperty("toSimChildren");
    }


    public void setToSimParent(SimulationDAO toSimParent) {
        setToOneTarget("toSimParent", toSimParent, true);
    }

    public SimulationDAO getToSimParent() {
        return (SimulationDAO)readProperty("toSimParent");
    }


}
