package mit.simulation.climate.dao;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _MetaDataDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MetaDataDAO extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EXTERNAL_PROPERTY = "external";
    public static final String ID_PROPERTY = "id";
    public static final String INDEXING_ID_PROPERTY = "indexingId";
    public static final String INTERNALNAME_PROPERTY = "internalname";
    public static final String LABELS_PROPERTY = "labels";
    public static final String NAME_PROPERTY = "name";
    public static final String PROFILE_PROPERTY = "profile";
    public static final String UNITS_PROPERTY = "units";
    public static final String VARCONTEXT_PROPERTY = "varcontext";
    public static final String VARTYPE_PROPERTY = "vartype";
    public static final String META_TO_DEFAULTS_PROPERTY = "metaToDefaults";
    public static final String META_TO_VARIABLE_PROPERTY = "metaToVariable";
    public static final String TO_INDEXED_PROPERTY = "toIndexed";
    public static final String TO_INDEXING_ID_PROPERTY = "toIndexingId";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setExternal(String external) {
        writeProperty("external", external);
    }
    public String getExternal() {
        return (String)readProperty("external");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setIndexingId(String indexingId) {
        writeProperty("indexingId", indexingId);
    }
    public String getIndexingId() {
        return (String)readProperty("indexingId");
    }

    public void setInternalname(String internalname) {
        writeProperty("internalname", internalname);
    }
    public String getInternalname() {
        return (String)readProperty("internalname");
    }

    public void setLabels(String labels) {
        writeProperty("labels", labels);
    }
    public String getLabels() {
        return (String)readProperty("labels");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setProfile(String profile) {
        writeProperty("profile", profile);
    }
    public String getProfile() {
        return (String)readProperty("profile");
    }

    public void setUnits(String units) {
        writeProperty("units", units);
    }
    public String getUnits() {
        return (String)readProperty("units");
    }

    public void setVarcontext(String varcontext) {
        writeProperty("varcontext", varcontext);
    }
    public String getVarcontext() {
        return (String)readProperty("varcontext");
    }

    public void setVartype(String vartype) {
        writeProperty("vartype", vartype);
    }
    public String getVartype() {
        return (String)readProperty("vartype");
    }

    public void setMetaToDefaults(MetaDataDefaultsDAO metaToDefaults) {
        setToOneTarget("metaToDefaults", metaToDefaults, true);
    }

    public MetaDataDefaultsDAO getMetaToDefaults() {
        return (MetaDataDefaultsDAO)readProperty("metaToDefaults");
    }


    public void addToMetaToVariable(VariableDAO obj) {
        addToManyTarget("metaToVariable", obj, true);
    }
    public void removeFromMetaToVariable(VariableDAO obj) {
        removeToManyTarget("metaToVariable", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VariableDAO> getMetaToVariable() {
        return (List<VariableDAO>)readProperty("metaToVariable");
    }


    public void addToToIndexed(MetaDataDAO obj) {
        addToManyTarget("toIndexed", obj, true);
    }
    public void removeFromToIndexed(MetaDataDAO obj) {
        removeToManyTarget("toIndexed", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MetaDataDAO> getToIndexed() {
        return (List<MetaDataDAO>)readProperty("toIndexed");
    }


    public void setToIndexingId(MetaDataDAO toIndexingId) {
        setToOneTarget("toIndexingId", toIndexingId, true);
    }

    public MetaDataDAO getToIndexingId() {
        return (MetaDataDAO)readProperty("toIndexingId");
    }


}
