package mit.simulation.climate.dao;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _TupleDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TupleDAO extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String SEQ_PROPERTY = "seq";
    public static final String TUPLE_VALUES_PROPERTY = "tupleValues";
    public static final String TUPLES_TO_VARIABLE_PROPERTY = "tuplesToVariable";

    public static final String ID_PK_COLUMN = "id";

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setSeq(Integer seq) {
        writeProperty("seq", seq);
    }
    public Integer getSeq() {
        return (Integer)readProperty("seq");
    }

    public void addToTupleValues(TupleValuesDAO obj) {
        addToManyTarget("tupleValues", obj, true);
    }
    public void removeFromTupleValues(TupleValuesDAO obj) {
        removeToManyTarget("tupleValues", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TupleValuesDAO> getTupleValues() {
        return (List<TupleValuesDAO>)readProperty("tupleValues");
    }


    public void setTuplesToVariable(VariableDAO tuplesToVariable) {
        setToOneTarget("tuplesToVariable", tuplesToVariable, true);
    }

    public VariableDAO getTuplesToVariable() {
        return (VariableDAO)readProperty("tuplesToVariable");
    }


}
