package mit.simulation.climate.dao;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _TupleValuesDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TupleValuesDAO extends CayenneDataObject {

    public static final String SEQ_PROPERTY = "seq";
    public static final String VALUE_PROPERTY = "value";
    public static final String VALUES_TO_TUPLE_PROPERTY = "valuesToTuple";

    public static final String ID_PK_COLUMN = "id";

    public void setSeq(Integer seq) {
        writeProperty("seq", seq);
    }
    public Integer getSeq() {
        return (Integer)readProperty("seq");
    }

    public void setValue(Double value) {
        writeProperty("value", value);
    }
    public Double getValue() {
        return (Double)readProperty("value");
    }

    public void setValuesToTuple(TupleDAO valuesToTuple) {
        setToOneTarget("valuesToTuple", valuesToTuple, true);
    }

    public TupleDAO getValuesToTuple() {
        return (TupleDAO)readProperty("valuesToTuple");
    }


}
