package mit.simulation.climate.dao;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _UserDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserDAO extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String USERNAME_PROPERTY = "username";
    public static final String USER_TO_SCENARIO_PROPERTY = "userToScenario";

    public static final String ID_PK_COLUMN = "id";

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }

    public void addToUserToScenario(ScenarioDAO obj) {
        addToManyTarget("userToScenario", obj, true);
    }
    public void removeFromUserToScenario(ScenarioDAO obj) {
        removeToManyTarget("userToScenario", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ScenarioDAO> getUserToScenario() {
        return (List<ScenarioDAO>)readProperty("userToScenario");
    }


}
