/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package mit.excelwrapper.model;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import mit.excelwrapper.model.auto._ExcelModel;

import org.apache.commons.httpclient.NameValuePair;

/**
 * <p>
 * ExcelModel object. It is generated by cayenne modeler initially. It is to add some help function.
 * </p>
 * <p>
 * <b>Thread Safety</b> This is a data object thus it is not thread safe.
 * </p>
 *
 * @author TCSDEVELOPER
 * @version 1.0
 */
public class ExcelModel extends _ExcelModel {
    /**
     * <p>
     * Serial version UID.
     * </p>
     */
    private static final long serialVersionUID = 3366047364655762806L;

    /**
     * <p>
     * param list field. This is to retain some param information from excel.
     * </p>
     */
    private List<List<NameValuePair>> paramList;

    /**
     * <p>
     * Gets param list.
     * </p>
     *
     * @return the param list
     */
    public List<List<NameValuePair>> getParamList() {
        return paramList;
    }

    /**
     * <p>
     * Sets the param list.
     * </p>
     *
     * @param paramList the param list
     */
    public void setParamList(List<List<NameValuePair>> paramList) {
        this.paramList = paramList;
    }

    /**
     * <p>
     * Helper function to return a map of input param keyed by internal name.
     * </p>
     *
     * @return the input param map keyed by internal name
     */
    public Map<String, InputParam> getInputParamMap() {
        Map<String, InputParam> map = new HashMap<String, InputParam>();
        for (InputParam param : getInputParams()) {
            map.put(param.getInternalName(), param);
        }
        return map;
    }
}
