/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package mit.excelwrapper.model;

import mit.excelwrapper.model.auto._OutputParam;

/**
 * <p>
 * OutputParam object. It is generated by cayenne modeler initially. It is to add some help function.
 * </p>
 * <p>
 * <b>Thread Safety</b> This is a data object thus it is not thread safe.
 * </p>
 *
 * @author TCSDEVELOPER
 * @version 1.0
 */
public class OutputParam extends _OutputParam {
    /**
     * <p>
     * Serial version UID.
     * </p>
     */
    private static final long serialVersionUID = 3366047364655762803L;
}
