package mit.simulation.climate.dao;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _MetaDataDefaultsDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MetaDataDefaultsDAO extends CayenneDataObject {

    public static final String DEFAULT_PROPERTY = "default";
    public static final String MAX_PROPERTY = "max";
    public static final String MIN_PROPERTY = "min";
    public static final String TO_META_DATA_PROPERTY = "toMetaData";

    public static final String ID_PK_COLUMN = "id";

    public void setDefault(Double _default) {
        writeProperty("default", _default);
    }
    public Double getDefault() {
        return (Double)readProperty("default");
    }

    public void setMax(Double max) {
        writeProperty("max", max);
    }
    public Double getMax() {
        return (Double)readProperty("max");
    }

    public void setMin(Double min) {
        writeProperty("min", min);
    }
    public Double getMin() {
        return (Double)readProperty("min");
    }

    public void setToMetaData(MetaDataDAO toMetaData) {
        setToOneTarget("toMetaData", toMetaData, true);
    }

    public MetaDataDAO getToMetaData() {
        return (MetaDataDAO)readProperty("toMetaData");
    }


}
