package mit.excelwrapper.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import mit.excelwrapper.model.InputParam;
import mit.excelwrapper.model.OutputParam;

/**
 * Class _ExcelModel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExcelModel extends CayenneDataObject {

    public static final String FORMAT_PROPERTY = "format";
    public static final String ID_PROPERTY = "id";
    public static final String PATH_PROPERTY = "path";
    public static final String WORKSHEET_PROPERTY = "worksheet";
    public static final String INPUT_PARAMS_PROPERTY = "inputParams";
    public static final String OUTPUT_PARAMS_PROPERTY = "outputParams";

    public static final String ID_PK_COLUMN = "ID";

    public void setFormat(String format) {
        writeProperty("format", format);
    }
    public String getFormat() {
        return (String)readProperty("format");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setPath(String path) {
        writeProperty("path", path);
    }
    public String getPath() {
        return (String)readProperty("path");
    }

    public void setWorksheet(Integer worksheet) {
        writeProperty("worksheet", worksheet);
    }
    public Integer getWorksheet() {
        return (Integer)readProperty("worksheet");
    }

    public void addToInputParams(InputParam obj) {
        addToManyTarget("inputParams", obj, true);
    }
    public void removeFromInputParams(InputParam obj) {
        removeToManyTarget("inputParams", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InputParam> getInputParams() {
        return (List<InputParam>)readProperty("inputParams");
    }


    public void addToOutputParams(OutputParam obj) {
        addToManyTarget("outputParams", obj, true);
    }
    public void removeFromOutputParams(OutputParam obj) {
        removeToManyTarget("outputParams", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<OutputParam> getOutputParams() {
        return (List<OutputParam>)readProperty("outputParams");
    }


}
