CREATE TABLE ExcelModel (ID VARCHAR(128) NOT NULL, Name VARCHAR(64) NOT NULL, Path VARCHAR(128) NOT NULL, PRIMARY KEY (ID)) ENGINE=InnoDB
;

CREATE TABLE InputParam (ColNum INT NOT NULL, Description VARCHAR(1024) NULL, ID VARCHAR(64) NOT NULL, ModelID VARCHAR(64) NOT NULL, Name VARCHAR(64) NOT NULL, RowNum INT NOT NULL, PRIMARY KEY (ID), KEY (ModelID)) ENGINE=InnoDB
;

CREATE TABLE OutputParam (ColNum INT NOT NULL, Description VARCHAR(1024) NULL, ID VARCHAR(128) NOT NULL, ModelID VARCHAR(128) NOT NULL, Name VARCHAR(128) NOT NULL, NumColumns INT NOT NULL, NumRows INT NOT NULL, RowNum INT NOT NULL, PRIMARY KEY (ID), KEY (ModelID)) ENGINE=InnoDB
;

CREATE TABLE AUTO_PK_SUPPORT (  TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID BIGINT NOT NULL, UNIQUE (TABLE_NAME))
;

DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ('ExcelModel', 'InputParam', 'OutputParam')
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('ExcelModel', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('InputParam', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('OutputParam', 200)
;

