package com.ext.portlet.plans;

public enum UpdateType {
    CREATED, DESCRIPTION_UPDATED, NAME_UPDATED, SCENARIO_UPDATED, PLAN_TYPE_UPDATED, MB_GROUP_UPDATED, PLAN_GROUP_UPDATED, PLAN_POSITIONS_UPDATED, MODEL_UPDATED
}
