package mit.simulation.climate.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import mit.simulation.climate.dao.SimulationDAO;
import mit.simulation.climate.dao.VariableDAO;

/**
 * Class _ScenarioDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ScenarioDAO extends CayenneDataObject {

    public static final String CREATION_PROPERTY = "creation";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String STATE_PROPERTY = "state";
    public static final String USER_PROPERTY = "user";
    public static final String SCENARIO_OUTPUT_TO_VARS_PROPERTY = "scenarioOutputToVars";
    public static final String SCENARIO_TO_INPUT_VARS_PROPERTY = "scenarioToInputVars";
    public static final String SCENARIO_TO_SIMULATION_PROPERTY = "scenarioToSimulation";

    public static final String ID_PK_COLUMN = "id";

    public void setCreation(Date creation) {
        writeProperty("creation", creation);
    }
    public Date getCreation() {
        return (Date)readProperty("creation");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setId(Long id) {
        writeProperty("id", id);
    }
    public Long getId() {
        return (Long)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }

    public void setUser(String user) {
        writeProperty("user", user);
    }
    public String getUser() {
        return (String)readProperty("user");
    }

    public void addToScenarioOutputToVars(VariableDAO obj) {
        addToManyTarget("scenarioOutputToVars", obj, true);
    }
    public void removeFromScenarioOutputToVars(VariableDAO obj) {
        removeToManyTarget("scenarioOutputToVars", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VariableDAO> getScenarioOutputToVars() {
        return (List<VariableDAO>)readProperty("scenarioOutputToVars");
    }


    public void addToScenarioToInputVars(VariableDAO obj) {
        addToManyTarget("scenarioToInputVars", obj, true);
    }
    public void removeFromScenarioToInputVars(VariableDAO obj) {
        removeToManyTarget("scenarioToInputVars", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VariableDAO> getScenarioToInputVars() {
        return (List<VariableDAO>)readProperty("scenarioToInputVars");
    }


    public void setScenarioToSimulation(SimulationDAO scenarioToSimulation) {
        setToOneTarget("scenarioToSimulation", scenarioToSimulation, true);
    }

    public SimulationDAO getScenarioToSimulation() {
        return (SimulationDAO)readProperty("scenarioToSimulation");
    }


}
