/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package mit.excelwrapper.model;

import mit.excelwrapper.DataType;
import mit.excelwrapper.Utils;
import mit.excelwrapper.model.auto._InputParam;


/**
 * <p>
 * InputParam object. It is generated by cayenne modeler initially. It is to add some help function.
 * </p>
 * <p>
 * <b>Thread Safety</b> This is a data object thus it is not thread safe.
 * </p>
 *
 * @author TCSDEVELOPER
 * @version 1.0
 */
public class InputParam extends _InputParam {
    /**
     * <p>
     * Serial version UID.
     * </p>
     */
    private static final long serialVersionUID = 3366047364655762805L;

    /**
     * <p>
     * Gets the data type in <code>DataType</code> enum.
     *
     * @return the <code>DataType</code> enum value
     */
    public DataType getDataTypeEnum() {
        return DataType.valueOf(getDataType());
    }

    /**
     * <p>
     * It provides an extra validation on dataType value.
     * </p>
     *
     * @param dataType the data type value
     *
     * @throw IllegalArgumentException if the value is null or invalid
     */
    @Override
    public void setDataType(String dataType) {
        Utils.checkNull(dataType, "dataType");
        // IAE will be thrown if the datatype value is invalid
        DataType.valueOf(dataType);
        super.setDataType(dataType);
    }
}
