package cayenne_classes;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ExcelModelDAO was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExcelModelDAO extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String PATH_PROPERTY = "path";
    public static final String WORKSHEET_PROPERTY = "worksheet";
    public static final String TO_INPUT_PARAM_PROPERTY = "toInputParam";
    public static final String TO_OUTPUT_PARAMS_PROPERTY = "toOutputParams";

    public static final String ID_PK_COLUMN = "ID";

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPath(String path) {
        writeProperty("path", path);
    }
    public String getPath() {
        return (String)readProperty("path");
    }

    public void setWorksheet(Integer worksheet) {
        writeProperty("worksheet", worksheet);
    }
    public Integer getWorksheet() {
        return (Integer)readProperty("worksheet");
    }

    public void addToToInputParam(InputParamDAO obj) {
        addToManyTarget("toInputParam", obj, true);
    }
    public void removeFromToInputParam(InputParamDAO obj) {
        removeToManyTarget("toInputParam", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InputParamDAO> getToInputParam() {
        return (List<InputParamDAO>)readProperty("toInputParam");
    }


    public void addToToOutputParams(OutputParamDAO obj) {
        addToManyTarget("toOutputParams", obj, true);
    }
    public void removeFromToOutputParams(OutputParamDAO obj) {
        removeToManyTarget("toOutputParams", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<OutputParamDAO> getToOutputParams() {
        return (List<OutputParamDAO>)readProperty("toOutputParams");
    }


}
