/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package mit.excelwrapper.model;

import mit.excelwrapper.model.auto._ExcelFilesMap;

/**
 * <p>
 * ExcelFilesMap object. It is generated by cayenne modeler initially. It is to add some help function.
 * </p>
 * <p>
 * <b>Thread Safety</b> This is not thread safe.
 * </p>
 *
 * @author TCSDEVELOPER
 * @version 1.0
 */
public class ExcelFilesMap extends _ExcelFilesMap {
    /**
     * <p>
     * Map instance.
     * </p>
     */
    private static ExcelFilesMap instance;

    /**
     * <p>
     * Ctor.
     * </p>
     */
    private ExcelFilesMap() {
        // do nothing
    }

    /**
     * <p>
     * Gets the map instance.
     * </p>
     *
     * @return the instance.
     */
    public static ExcelFilesMap getInstance() {
        if (instance == null) {
            instance = new ExcelFilesMap();
        }

        return instance;
    }
}
